### ISSUE TITLE
More doc examples.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#12]
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Fri Feb 11 04:04:19 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/36_

----

### Is your feature request related to a problem? Please describe.

-

### Describe the solution you'd like

Add more doc examples when we have some interesting relational operators.

**Comment by mihaibudiu** [comment]
Fixed by #209
