### ISSUE TITLE
Curated collection of end-to-end demos

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#138]
- [ ] Test all demos in CI

**Comment by ryzhyk** [comment]
- [ ] Cleanup existing demos
- [ ] Add a few new demos

**Comment by blp** [comment]
- [ ] Fix generator in secops demo so that it doesn't run out of memory, by making it generate retractions

**Comment by blp** [comment]
- [ ] Time series enrichment demo is confusing because the data that it stores grows unboundedly

**Comment by blp** [comment]
- [ ] Fraud demo needs a dataset
- [ ] Green trip demo needs a dataset

**Comment by ryzhyk** [comment]
- [ ] document Python notebook as part of the fraud demo
