### ISSUE TITLE
[JIT] Comparison of RowLiteral containing NaN does not work

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/dbsp#146]
```
thread 'test20' panicked at 'assertion failed: `(left == right)`
  left: `Set([(RowLiteral { rows: [Nullable(Some(F64(NaN)))] }, 1), (RowLiteral { rows: [Nullable(None)] }, 1)])`,
 right: `Set([(RowLiteral { rows: [Nullable(Some(F64(NaN)))] }, 1), (RowLiteral { rows: [Nullable(None)] }, 1)])`', src/lib.rs:9377:5
```

This is related to #125 

Interestingly, I never had this problem with NaN in the Rust-based tests using F64.
I know that NaN is not supposed to be equal with itself.

**Comment by mihaibudiu** [comment]
Indeed, I could not reproduce this by a manual test. It may depend on how the NaN has been produced.
I could not even reproduce it by using 0.0/0.0, which is how the failing test produces the NaN.

**Comment by Kixiron** [comment]
I'm unsure how to address this without reproduction steps

**Comment by mihaibudiu** [comment]
To reproduce:
1. Comment-out the '@Ignore' in JitTests.java:
```
@Test @Override // @Ignore("NaN comparison does not work https://github.com/feldera/dbsp/issues/146")
    public void floatDivTest() {
```
2. in sql-to-dbsp-compiler/SQL-compiler run this command:
```
mvn test -Dtest=JitTests#floatDivTest
```
3. Now the reproduction is in sql-to-dbsp-compiler/temp. You can run it with just 'cargo test'.
