### ISSUE TITLE
Move time tracking to the circuit.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#15]
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Tue May 31 00:09:49 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/65_

Instead of having each operator track current time, move time tracking into the circuit.

**Comment by mihaibudiu** [comment]
Is this issue still relevant?

**Comment by ryzhyk** [comment]
This one is done.
