### ISSUE TITLE
[sql] Find and run more test suites

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#151]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Mon Oct 10 18:48:07 2022_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/39_

----

SqlLogicTest only tests integers, doubles, and strings

**Comment by mihaibudiu** [comment]
I will close this issue since it is too broad. We are working on postgres for now.
