### ISSUE TITLE
[sql] Calcite plans sometimes produce unnecessary columns which are projected away later

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#163]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Thu Mar 30 17:53:52 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/140_

----

This happens for joins and unnests, for example.
The compiler should "look ahead" and not generate the fields that are not needed.

**Comment by mihaibudiu** [comment]
The most egregious cases of this have been fixed in #218 through the use of the Projection visitor
