### ISSUE TITLE
[sql] We cannot support very large Decimal (Numeric) values

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#168]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Thu Feb 23 23:31:55 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/121_

----

There is no Rust library that supports big decimal values correctly.
Until there is one, we have to limit ourselves to 128-bit decimals.

**Comment by mihaibudiu** [comment]
I will close this one, because many SQL dialects have a similar limitation.
