### ISSUE TITLE
[sql] Set up an extendable Calcite parser

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#169]
<a href="https://github.com/lalithsuresh"><img src="https://avatars.githubusercontent.com/u/434651?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lalithsuresh](https://github.com/lalithsuresh)**
_Thu Feb 23 23:17:49 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/pull/120_

----

Workflow to extend the parser is:
* Update parserImpl.ftl with the new parser definitions
* Declare those new parser definitions in config.fmpp
* Use parser from code (see the added test file). It uses the generated parser, built when running `mvn package`.

----

_**[lalithsuresh](https://github.com/lalithsuresh)** included the following code: https://github.com/vmware/sql-to-dbsp-compiler/pull/120/commits_

**Comment by mihaibudiu** [comment]
Fixed by #210
