### ISSUE TITLE
[sql] Combine Calcite BABEL and DDL parsers

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#171]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Fri Feb 17 19:10:46 2023_
_Originally opened as https://github.com/vmware/sql-to-dbsp-compiler/issues/114_

----

 https://lists.apache.org/thread/nvlt0jfvvo0gpc5djw24xt8ss68k1ysl

Original problem: 
I am trying to parse a DDL statement such as CREATE VIEW V AS SELECT DATE_PART(YEAR, T) FROM TABLE.
If I am using the DDL parser factory, I can parse CREATE VIEW statements but not DATE_PART.
If I am using the BABEL parser factory, I can parse DATE_PART expressions but not CREATE VIEW.
Is there a way to get both?

**Comment by mihaibudiu** [comment]
Fixed by #210
