### ISSUE TITLE
`Date` deserialization is broken.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#175]
This [code](https://github.com/feldera/dbsp/blob/0211b620d0ef441b2ded6c72ae5da6f845a38c4c/sql-to-dbsp-compiler/lib/sqllib/src/timestamp.rs#L589) in `sqllib/src/timestamp.rs` doesn't parse dates correctly. I have a [repro](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ed6623ca278bfe74d1e4753601789c39) in the playground.

Changing `NaiveDateTime` to `NaiveDate` seems to fix it.

@gz

**Comment by mihaibudiu** [comment]
Funny, I was supposed to have a test for this stuff.

**Comment by ryzhyk** [comment]
This might be a recent regression (feature?) in `chrono`
