### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by gz** [feldera/dbsp#176]
- [ ] the python build + test should be a separate task (that depends onmanager build)
- [ ] a task should cache python dependencies
- [x] a task should cache maven dependencies
- [ ] the java build should only depend on base image and dependent task should only depend on the compiler jar file
- [ ] the test-python task should not build the sql compiler on its own every time (this is a Makefile.toml problem)
- [x] run SQL compiler tests in CI

**Comment by lalithsuresh** [comment]
You can mirror the task DAG in the Dockerfile.
