### ISSUE TITLE
[sql] Calcite optimizer incorrectly evaluates DATE_TRUNC

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/dbsp#217]
There is a test in PostgresDateTests which fails because of this: testDateTrunc().
Filed https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-5761 
The bug can be worked around by disabling the following optimization rule from the Hep Planner:
CoreRules.PROJECT_VALUES_MERGE

**Comment by bin-wang** [comment]
It seems this issue needs some update since the linked Calcite issue has been marked as solved in 1.35, while the `testDataTrunc()` has been removed for the tests. My impression is that DATE_TRUNC for Postgres is currently not supported. Maybe we should close this issue or update the title?

**Comment by mihaibudiu** [comment]
Yes, the test can't work anyway so I removed it

**Comment by bin-wang** [comment]
Well, there is one more thing: CoreRules.PROJECT_VALUES_MERGE was disabled referencing this issue. Should it be re-enabled?

**Comment by mihaibudiu** [comment]
I will reenable it to see if anything else breaks.

**Comment by mihaibudiu** [comment]
I have re-enabled this Calcite optimization, it wasn't really the root cause.
