### ISSUE TITLE
persistent and non-persistent pipeline state across restarts

### ISSUE THREAD

**Issue by gz** [feldera/dbsp#235]
We need to make sure pipeline DB state stays consistent across restarts... right now there are some pain points:

- If a program is compiled and the manager is restarted it loses the "compiled" status and the schema gets reset.. this might be awkward for users as they can now no longer start/stop the pipeline because the program isn't compiled (e.g., they need to go compile the program first).
- we can solve it with a dialog inthe UI (for pipeline edit that's what I do) but it's awkward also for API users and maybe there is a better way... like not reset the status across all programs on restart?
- pipeline also has a persistent status now (running/stopped etc.) in the db. when the manager restarts we don't reset the status but the pipeline may have disappeared.
- the fix might be to reset all the pipeline status to shutdown here. a better way may be to test what pipeline processes are still around and have means to discover them and then repopulate the db status?

**Comment by ryzhyk** [comment]
@gz , I can work on this.  I think this basically amounts to checking pipeline state and compiled artifact on restart. For the former, we probably need to have periodic health check in place anyway, so this is just a matter of running the health checks as part of initialization.

**Comment by lalithsuresh** [comment]
This would depend on the form factor, so the likely place for this type of code is within the specific runner types. For example, in the cloud-form factor, pipeline manager restarts should have no bearing on program status.

**Comment by ryzhyk** [comment]
Yes, this would be part of the runner trait.

**Comment by lalithsuresh** [comment]
@ryzhyk With https://github.com/feldera/dbsp/pull/421 done, should we close this issue? Or is there something else to add for pipeline restarts?

**Comment by ryzhyk** [comment]
We also discussed that I need to fix up the runner to start a monitoring thread per each running pipeline on startup.  So let's keep it open for now.

**Comment by lalithsuresh** [comment]
@ryzhyk #447 covers the runner sync on startup. Shall we close this issue?
