### ISSUE TITLE
End-to-end API tests.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#278]
Implement end-to-end tests that exercise Feldera via the pipeline manager API, including
- Deterministic straigh-line tests.
- Randomized tests.

Tests should work against the three main form factors:
- Local (compile and run DBSP on the host system).
- Docker-based.
- EKS-based.

**Comment by lalithsuresh** [comment]
I'll focus first on the deterministic tests.

It's less clear to me what we should focus on with randomized tests. The DB-specific model-based tests currently do a good job of testing whether a sequence of DB operations behave similarly to a simplified in-memory model. Given that the API is a thin wrapper around the DB, it's probably not worth duplicating a similar model-based approach for e2e tests.

Maybe reliability testing? E.g., generate a sequence of API calls, and compare two executions: 1) a fault-free run vs 2) a run where the pipeline-manager crashes one or more times in between?

**Comment by ryzhyk** [comment]
It certainly makes sense to start with deterministic tests.  This way you'll be able to focus on building a nice test framework that allows expressing test cases concisely and create many useful test scenarios.

> Given that the API is a thin wrapper around the DB, it's probably not worth duplicating a similar model-based approach for e2e tests.

That's not really the case.  It's true that the DB API mirrors a lot of the REST API, but REST endpoints do much more work: invoke the compiler, create/destroy pipelines, stream data, etc., and the goal of API tests is to exercise all this functionality. Model-based testing seems like a good approach here even if the model ends up being similar to the one we already have for the DB.  The model helps to generate meaningful sequences of operations and to check that the results are correct. It's a lot of work though, so we may want to start small.

I think reliability testing is also useful but complementary.

**Comment by lalithsuresh** [comment]
> It's a lot of work though, so we may want to start small.

Agreed.

The duplication and model maintenance is the key challenge. The model in this case will be pretty much identical to the DB one (struct with maps of in memory objects). Almost all the work and tedium in maintaining the current DB model is in lining up the shape of the responses to different inputs, as opposed to logic issues.

Ideally, we'd find a way to reuse the existing model.

**Comment by gz** [comment]
it should be possible to use the existing dbmodel as part of a larger model

**Comment by ryzhyk** [comment]
I honestly wouldn't obsess about model reuse in this case. There is some overlap but they are different enough that you'd be better off just building a new one for the API.  At least this is my hunch.

**Comment by ryzhyk** [comment]
> it should be possible to use the existing dbmodel as part of a larger model with composition

yep, this is probably the best approach

**Comment by lalithsuresh** [comment]
#292 adds deterministic tests and can work against different form factors. I'll create a separate issue for randomized ones.
