### ISSUE TITLE
REST API documentation cleanup + integration

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#279]
The end goal here is to generate the API section of the docs.feldera.com website.

- [ ] Automate publishing of the docs 
- [ ] Make sure the docs are correct, complete, user-friendly, use consistent terminology, contain examples (including examples of invoking the API from `curl`), etc.

**Comment by gz** [comment]
see also https://github.com/feldera/dbsp/issues/86

**Comment by ryzhyk** [comment]
Yep, especially this would be cool:

> The execute button in the REST API docs should work (e.g., there is an option to add multiple URLs one of them could be localhost:8080)

**Comment by lalithsuresh** [comment]
> Yep, especially this would be cool:
> 
> > The execute button in the REST API docs should work (e.g., there is an option to add multiple URLs one of them could be localhost:8080)

This might be hard to do without logging in and using a user's credentials to do render the correct curl command (e.g., endpoint + bearer token). It's how other API vendors handle it in their documentation.

**Comment by ryzhyk** [comment]
>This might be hard to do without logging in and using a user's credentials to do render the correct curl command (e.g., endpoint + bearer token). It's how other API vendors handle it in their documentation.

Yeah, that's the only way. 

> If we can display this documentation from a live deployment, then we might be able to do this. E.g., we click a button on the UI of a live deployment, which gives us the variables to populate when the user opens docs.feldera.io.

True, but also the docs on the website may be able to query the local deployment on `localhost`.

**Comment by gz** [comment]
auth+different URLs to pick from should be supported by the OpenAPI plugins that generates this stuff

e.g., we're using the first one currently but the second one might also be a (better) option:
https://github.com/cloud-annotations/docusaurus-openapi
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs

**Comment by lalithsuresh** [comment]
With #389 and #414 done, we can close this issue.
