### ISSUE TITLE
TopK and Sorting operators

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#28]
<a href="https://github.com/Kixiron"><img src="https://avatars.githubusercontent.com/u/25047011?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kixiron](https://github.com/Kixiron)**
_Fri Jul  8 20:19:25 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/104_

----

TopK (and sorting, being closely related) is a super important operator for streaming systems and databases as a whole, as is being able to sort data and so we should support both.
Both operations can be done in a linear and tree-like manner, we should probably offer both for greater flexibility. (The tree-like forms consist of partitioning the input data into `N` streams, sorting/topk-ing each stream and then recombining them via sort/topk in a tree until a single result is reached, this can allow for partial incrementality at the cost of memory)

**Comment by mihaibudiu** [comment]
TopK fixed by #73
Can we close this issue?
