### ISSUE TITLE
Running a pipeline removes its description in the Pipeline Mgmt page

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#283]
1. Go to Pipeline Mgmt. page
2. Create a pipeline
3. Add its name and description
4. Create another pipeline and add its name and description
5. Run the second pipeline
6. Descriptions are cleared for both pipelines

**Comment by Karakatiza666** [comment]
Cannot reproduce - tried by creating a second pipeline using SecOps program, delete both and create a new pair of those, and two pipelines without a program. Please let me know If anyone can reproduce

**Comment by gz** [comment]
Agree, this seems fixed, I also made the name/desc editable in the table now.
