### ISSUE TITLE
Add a /dev/null output connector

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#287]
It'll be nice to add a /dev/null destination for any view to able to introspect the data in the UI.

**Comment by ryzhyk** [comment]
This shouldn't be needed.  The UI should be able to introspect any view or table, whether it has connectors or not. Not sure why it doesn't today.

@gz

**Comment by mohsinbeg** [comment]
Introspecting tables throws exception in docker and UI shows a spinner that never completes.

**Comment by ryzhyk** [comment]
Yes, this feature hasn't been implemented yet (see #101)

**Comment by gz** [comment]
closing as duplicate of #101
