### ISSUE TITLE
Start Pipeline throws an exception while associated SQL is still compiling

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#289]
1. Create a SQL program with one table and one view
2. Allow it to compile
3. Navigate to Pipeline Builder and create a new pipeline
4. Navigate to Existing Program and edit the program
5. Paste in SecOps SQL into the program. Confirm it has started to compile but not finished.
6. Navigate to Pipeline Management, confirm it's status is `INACTIVE` and click `Start Pipeline` icon.

**Comment by gz** [comment]
should be resolvable with
- https://github.com/feldera/dbsp/issues/235
and
- https://github.com/feldera/dbsp/issues/80

**Comment by gz** [comment]
- [ ] In pipeline view table, if the pipeline is in shutdown state, and the program attached to the pipeline is not in success state (compiling, pending etc.) we should not allow the user to start the pipeline --  e.g. we can change status in the table to program compiling and don't show the play button to start the pipeline.
