### ISSUE TITLE
Count operator

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#30]
<a href="https://github.com/Kixiron"><img src="https://avatars.githubusercontent.com/u/25047011?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kixiron](https://github.com/Kixiron)**
_Sun Jul 24 23:02:41 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/125_

----

We need to add a `.count()` operator that counts the number of values for any given key, e.g. `(K, V).count() -> (K, isize)`

**Comment by blp** [comment]
This is PR #112.
