### ISSUE TITLE
Vocabulary: "connectors" vs "adapters"?

### ISSUE THREAD

**Issue by blp** [feldera/dbsp#355]
While working on documentation, I've found that it's a little awkward to talk about "input connectors" and "output connectors" because they only connect on one side. It's hard to write the documentation to avoid saying that you have to connect the connector (to a pipeline). Instead, I've been talking about "mapping" connectors to tables or views. It would be less awkward if we talked about input adapters and output adapters. Then it would be natural to say that an input adapter gets connected to a table and an output adapter gets connected to a view.

**Comment by lalithsuresh** [comment]
Another option is to say data sources and sinks.

Then we can say "data sources connect to tables, and sinks to views".

**Comment by ryzhyk** [comment]
Can we say "attach connector"?

As far as I can tell, "connector" is the industry-standard term at this point, so we probably shouldn't go against the flow.  We could for example talk about source and sink connectors and abbreviate them as "sources" and "sinks" when appropriate.

And yes, "mapping" connectors sounds a bit awkward.

**Comment by blp** [comment]
"attach" is good vocabulary. Thanks @ryzhyk

**Comment by blp** [comment]
I checked in docs that use "attach" as the verb to add a "connector" to a pipeline.
