### ISSUE TITLE
Reload is broken for viewing programs and pipelines

### ISSUE THREAD

**Issue by blp** [feldera/dbsp#362]
If I go to Existing Programs or to Pipeline Management, then click on a pencil icon to view the details, then hit <kbd>Ctrl+R</kbd> or the browser's reload button, I just get "not found":
![image](https://github.com/feldera/dbsp/assets/613451/789b2b95-5c65-4cb0-86b8-ecdbfe3a88f7)
I still get the same thing if I click the browser's back button, although another reload at that point gives me the right screen.

**Comment by gz** [comment]
Duplicae of https://github.com/feldera/dbsp/issues/270
