### ISSUE TITLE
Docusaurus should support math

### ISSUE THREAD

**Issue by mihaibudiu** [feldera/dbsp#367]

**Comment by blp** [comment]
See the `math-docs` branch.

**Comment by blp** [comment]
This is how it renders for me.
![image](https://github.com/feldera/dbsp/assets/613451/0792dd88-6db3-4f25-bdca-3f92a7976cd6)

**Comment by mihaibudiu** [comment]
We should put the Riemann integral our our home page

**Comment by blp** [comment]
OK, I added this to the `demo-docs` branch now.

**Comment by gz** [comment]
uh looks like you figured it out, but just in case: https://docusaurus.io/docs/next/markdown-features/math-equations

**Comment by blp** [comment]
I think this is fixed.
