### ISSUE TITLE
Naming of incremental operators is not consistent

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#37]
<a href="https://github.com/mihaibudiu"><img src="https://avatars.githubusercontent.com/u/19397042?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mihaibudiu](https://github.com/mihaibudiu)**
_Wed Oct 19 00:30:54 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/217_

----

For example, we have join and join_incremental, distinct and distinct_incremental, but aggregate and stream_aggregate.

**Comment by blp** [comment]
> > [<img alt="" width="48" height="48" src="https://avatars.githubusercontent.com/u/8323135?v=4">](https://github.com/ryzhyk) **Comment by [ryzhyk](https://github.com/ryzhyk)** _Wed Oct 19 00:38:08 2022_
> > > If they are for testing, perhaps they should not be public if it is possible.
> > 
> > 
> > Yes, I think they should be hidden.
> 
> PR #93 makes `join_incremental` hidden.

It's merged now.

**Comment by mihaibudiu** [comment]
Can we close this issue?
