### ISSUE TITLE
Wrong URLs generated by swagger UI

### ISSUE THREAD

**Issue by gz** [feldera/dbsp#376]
It seems that https://github.com/feldera/dbsp/commit/3d30dd1d41f92f1cc8ac8418ee0d47471d9c4f0b broke the URLs generated by swagger UI, it no longer assumes the /v0/ in the URL for generating requests so you can no longer execute requests through the web-interface. 

Is there a way to fix this while keeping scopes, maybe @lalithsuresh knows?

**Comment by lalithsuresh** [comment]
Normally with OpenAPI this is trivial to address, you add a basePath to the OpenAPI spec. With Utopia, I'm not sure how to do that. Utopia does not interact well with scopes unfortunately.

**Comment by lalithsuresh** [comment]
Relevant issue: https://github.com/juhaku/utoipa/issues/283
