### ISSUE TITLE
[RFC] Support for JSON input/output.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#385]
## Scope

We propose a design for ingesting and outputting JSON-formatted data, including support for insertions, deletions, weights, and upserts  (see #347). This design will be implemented as a new data format in the `dbsp_adapters` crate. The design incorporates initial support for Debezium CDC JSON format.  The intention is to extend this in the future, so we don't need to implement a separate adapter for that, while also being able to support non-CDC JSON data. 

## Representation of a single record

There are several ways to represent a record in a SQL table in JSON.

* Option 1: Map
  ```
  { "column1": val1, "column2": val2 }
  ```
  where `column1` and `column2` are names of columns in the table, and `val1` and `val2` are JSON encodings of the corresponding column types.

* Option 2: Array
  ```
  [val1, val2]
  ```
  The order of columns should by default match the order in the SQL declaration (but can potentially be overridden via the stream metadata mechanism discussed below).

* Option 3: Raw
  This encoding is only applicable to single-column tables, in which case the entire record can be represented as a  JSON-encoded value of this column without any envelope:
  ```
  val
  ```

### Discussion

Each encoding has its own advantages and limitation.

* Option 1 is arguably the easiest to parse for a human.  It also allows skipping nullable columns.  
* Option 2 is more concise and allows more efficient parsing.
* Option 3 allows consuming data from external sources without pre-processing (all parsing will need to happen inside DBSP).

Note also that the parser can automatically distinguish the first two encodings (one is a map, the other -- an array), so the sender doesn't have to provide any additional metadata to identify the type of encoding (see metadata discussion below); in contrast, the raw encoding (Option 3) cannot always be automatically detected.

## Representation of updates

In general an update in DBSP is a `(value, weight)` pair. There are again multiple ways to represent this tuple in JSON.

* Option 1: Insert-only

  This representation is applicable to streams that consist of inserts only (i.e., updates with weight +1), e.g., streams of external events.  Such updates can be represented as records formatted using one of the three encodings discussed above, without any additional envelope, with the weight component being implicit.

* Option 2: Unit weights
  This encoding is applicable in the common case of a stream that carries updates with unit weights `(+1, -1)` only. 
  ```
  { "insert": record, table: "my_table" }
  { "delete": record, table: "my_table" }
  { "delete_key": key, table: "my_table" }
  ```
  The first two are self-explanatory. The third update type is applicable to an indexed collection with upsert semantics of updates, where records can be deleted by key.  We don't have such tables now, but I think we should represent tables with `PRIMARY KEY`'s this way in the future. The `table` field can be omitted if the connector is bound to a specific table (via a connector config parameter).

* Option 3: Arbitrary weights
  ```
  {
    "table": "my_table"
    "data": record,
    "weight": -3
  }
  ```

* Option 4: Change Data Capture (CDC)-compatible representation (based on the [Debezium JSON CDC](https://debezium.io/documentation/reference/1.6/connectors/mysql.html) format, which seems like the closest thing to a standard in this space)
  
  ```
  {
    payload: {
      "before": record,
      "after": record,
      "op": "c"|"d"|"u",
      "source": {
        "table": "table_name"
      }
    }
  }
  ```

  Where "c" (for Create) inserts a row specified in "after" with weight +1, "d" (for Delete) deletes the row in "before" (weight = -1), and "u" (for Update) deletes the "before" row and inserts the "after" row. The "before" row must be `null` when "op" is "c".  The "after" row must be `null` when "op" is "d". If the target table has a unique key, the "before" record contains the values of columns that form the key only.  In this format, individual rows use the Map representation (see above).

Note that encodings 2, 3, and 4 can be distinguished automatically by the parser and can even be mixed in the same data stream; however the insert-only encoding cannot in general be detected automatically.

## Representation of a group of updates

Multiple updates can be represented as 

* Option 1: JSON array `[update1, update2, ...]`
* Option 2: Newline-delimited stream of updates:
  ```
  update1
  update2
  ...
  ```

## Stream metadata

Based on the above discussion, it makes sense to support multiple encodings for both individual records and updates, which means that each input data stream may require additional metadata for the parser to identify the encoding used.  Likewise, an output stream must be configured with encoding to apply to the output data.

This metadata can be part of a JSON connector configuration. In general, any connector configuration specifies a data transport and a data format. In this case the format is JSON, with format metadata specified as a set of additional configuration attributes.

The metadata can also be sent inline as a special JSON record, overriding the default configured for the stream.

## Implementation considerations

- I believe all of this can be built on top of our current serde-based connectors, but we should probably start with a subset of the features. I propose:
  - Supported single-record encodings: array-based (I believe this is what `serde` generates by default for tuple types specified by the SQL compiler), and raw (will enable us to work with external data sources that don't comply with our expected format).
  - Supported update encodings: insert-only (useful with external data sources), unit weights (no upserts yet), arbitrary weights.
  - Group of updates: It should be easy enough to support both formats (newline-delimited and array-based).
  - Metadata representation: provide metadata as part of connection configuration, no inline metadata for now.
- Once JSON support is ready, it should become the default way for the UI to communicate with the backend for data input and output.

**Comment by mihaibudiu** [comment]
Ideally we should adopt a standard if it exists. 
CDC systems must do this already.

**Comment by ryzhyk** [comment]
> Ideally we should adopt a standard if it exists. CDC systems must do this already.

That's a good point. We won't be able to support full-blown CDC, which has a lot of stuff around schema management and schema changes, any time soon, but we can support a subset.

CDC also doesn't have all the features we need.  Most importantly, it requires a CDC-compliant sender and cannot be used to consume some custom application-specific JSON data, which is an important design goal here.

One very nice feature that CDC supports that's missing in my design above is the ability to feed multiple tables from the same stream (it's not rocket science, you just need to include table name in each message).

I will refine the RFC to add a form of CDC compatibility to it. The goal is to design this feature in such a way that we won't need to build a separate JSON CDC connector in the future, but just be able to use the same connector (with some improvements)

**Comment by gz** [comment]
> Representation of a single record
Following Postel's law, we should be liberal in what we accept e.g., I think we should accept both Option 1 and 2 as inputs. Not sure about Option 3 if it's really needed?

> Representation of updates
> Option 3: Arbitrary weights
IMO weights are an implementation specific detail of `dbsp`. I don't think exposing it is a good idea and might make future changes harder.

**Comment by ryzhyk** [comment]
>Following Postel's law, we should be liberal in what we accept e.g., I think we should accept both Option 1 and 2 as inputs. Not sure about Option 3 if it's really needed?

Option 3 is important, so we can take an arbitrary json and stick into a table like this: https://materialize.com/docs/sql/create-source/#json

There is also a version of Option 2 where columns can come in an order that is not consistent with the SQL declaration, which requires an additional piece of metadata.

A lot of external data sources  will likely be this way.

> IMO weights are an implementation specific detail of dbsp. I don't think exposing it is a good idea and might make future changes harder.

Ideally, yes, with ddlog we found that people get confused by weights.  But for outputs specifically enforcing unit weights requires applying `distinct` to all output relations (which we might be doing already in SQL?), otherwise you may see arbitrary weights, which cannot be just ignored.

Also, arbitrary weights may be useful if we want to chain multiple DBSP's somehow.

**Comment by gz** [comment]
There is also a conflict with `weight` if a field in a table is already called `weight` we should maybe prefix it with something that's not a valid sql field identifier.

**Comment by ryzhyk** [comment]
It would only be ambiguous if we tried to guess the format dynamically, but the idea is that it will be specified as part of connector config or as a separate metadata record in the stream.  When the representation with explicit `weight`'s is used, the actual data will be stored in the `data` field of the struct, eliminating potential name clash.

**Comment by lalithsuresh** [comment]
@ryzhyk any reference points for how other systems handle this?

**Comment by ryzhyk** [comment]
- [Debezium CDC format](https://debezium.io/documentation/reference/1.6/connectors/mysql.html)
- [Flink](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/datastream/formats/json/) doesn't seem to define any envelope for JSON, it simply deserializes raw values; one can convert values to SQL inserts and deletes programmatically.
- [Timeplus JSON ingest](https://docs.timeplus.com/ingest-api#options)
- [RisingWave](https://www.risingwave.dev/docs/current/sql-create-source/) supports a bunch of CDC and other JSON formats. With the framework I'm building we should be able to easily add support for any of these in the future.
