### ISSUE TITLE
SQL Compiler should not optimize away unused tables

### ISSUE THREAD

**Issue by gz** [feldera/dbsp#386]
I ran into this when compiling the secops demo. There are some tables that aren't used by views in this example. But since the tables exist in the schema, the UI displays them. For a user (me), it is confusing that I couldn't send anything to the table or read from. Instead it throws an  error that the table doesn't exist. 
I think it's also valuable for a user to be able to send data to unused tables just for testing (first thing one might do is create a table and try to send some data to it). So it would be good if tables that are declared in the SQL don't get optimized away.

**Comment by mihaibudiu** [comment]
Use the -alltables flag. Documented here https://github.com/feldera/dbsp/blob/585a1926a6d3a0f8176dc80db5e906ec7d095400/docs/docs/guides/sql.md?plain=1#L87
