### ISSUE TITLE
Changes diff disappears on docker restart

### ISSUE THREAD

**Issue by mohsinbeg** [feldera/dbsp#387]
1. Create a SQL program
2. Create a pipeline with the program
3. Run the pipeline
4. Pause the pipeline
5. Make changes in SQL program by adding a column alias
6. Make changes in pipeline config by removing two input connections.
7. Navigate to `Pipeline Management` and click on the changes button. View Config and SQL changes in the modal dialog. D
8. Shutdown docker
9. Start docker
10. SQL Program compilation starts.
11. Go back to `Pipeline Management`. Previously pending config changes are reverted.

**Comment by gz** [comment]
I can't reproduce for me config changes are not reverted. What are the commands you run to shutdown/restart docker?

**Comment by blp** [comment]
If you start up `docker compose` with `--profile demo`, then it will delete and recreate the secops project. That could be the issue here.

**Comment by mohsinbeg** [comment]
```
dbsp-db-1        | 2023-07-24 16:55:30.772 UTC [27] LOG:  checkpoint starting: time

dbsp-db-1        | 2023-07-24 16:55:31.399 UTC [27] LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.606 s, sync=0.009 s, total=0.627 s; sync files=7, longest=0.003 s, average=0.002 s; distance=13 kB, estimate=27 kB

^CGracefully stopping... (press Ctrl+C again to force)

Aborting on container exit...
[+] Stopping 4/4
 ✔ Container dbsp-demo-1      Stopped                                                                                             0.0s 
 ✔ Container dbsp-redpanda-1  Stopped                                                                                             1.4s 
 ✔ Container dbsp-dbsp-1      Stopped                                                                                             1.2s 
 ✔ Container dbsp-db-1        Stopped                                                                                             0.3s 
canceled```

**Comment by gz** [comment]
It looks like you ran with `--profile demo up` which according to @blp recreates the secops demo. So maybe this needs to be documented for a user that this command is only to be used on initialization. Or is there another way so it doesn't reinitialize this @lalithsuresh?

**Comment by blp** [comment]
> So maybe this needs to be documented for a user that this command is only to be used on initialization. 

It's documented:

`````markdown
## Restart the demo

If you start and then stop the demo as described above, you can
restart it a few different ways:

* To restart it without changes, run:

   ```bash
   docker compose up
   ```

* Run this command to reload the demo afresh, while discarding all
  additional programs, connectors and pipelines you've added:

   ```bash
   docker compose --profile demo up
   ```

* Run this command to upgrade to a new version of the demo, while
  discarding all additional programs, connectors and pipelines you've
  added:

  ```bash
  docker compose --profile demo up --pull always --force-recreate -V
  ```
`````

**Comment by lalithsuresh** [comment]
@gz I don't think the SecOps demo code is fully idempotent. It'll recreate all the API objects, but it might insert even more data into Redpanda.

**Comment by mohsinbeg** [comment]
1. Make SQL program changes.
2. Wait for SQL to finish compiling
3. Shutdown docker with `CTRL-C`
4. Start docker with `docker compose up`
5. Navigate to Pipeline Management
6. Click the yellow colored Changes button shows a (2) decoration
7. Click changes shows a SQL compile issue

 
![image](https://github.com/feldera/dbsp/assets/28739668/f2563795-e60d-4c67-9f65-e5acc3cff61a)
![image](https://github.com/feldera/dbsp/assets/28739668/fe12a752-747c-4890-a9fd-b7d8acb4fa7d)

**Comment by gz** [comment]
If docker is restarted the compilation state of the program is currently lost reset (there is an issue for it here https://github.com/feldera/dbsp/issues/235). Right now you have to navigate to programs and compile that program again. Once #235 is fixed this should no longer be necessary.

**Comment by mohsinbeg** [comment]
> But it looks like this is now a different issue/duplicate than originally reported (e.g., the change is still here?)

With `docker compose up` old changes are viewable. Thank you @gz @blp for clarifying. I suspect that others will make the same change even after reading the docs, like I did. It's incorrect but much easier to execute the previous docker command in bash history to restart.

**Comment by blp** [comment]
> With `docker compose up` old changes are viewable. Thank you @gz @blp for clarifying. I suspect that others will make the same change even after reading the docs, like I did. It's incorrect but much easier to execute the previous docker command in bash history to restart.

Possibly it would be less surprising behavior if  `--project demo`were idempotent and it takes `--force-recreate -V` (or whatever) to clear everything out. I wouldn't object to that change.
