### ISSUE TITLE
Split benchmark demos into separate crates

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#39]
<a href="https://github.com/Kixiron"><img src="https://avatars.githubusercontent.com/u/25047011?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kixiron](https://github.com/Kixiron)**
_Wed Nov  9 22:20:01 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/231_

----

Currently we have a lot of "benchmarks" that aren't actually benchmarks, they're full fledged binaries. Currently we have them set up as benchmarks which forces us to add their dependencies as dev dependencies to `dbsp` as well as making custom feature sets just for the benchmarks. This can all be avoided by just making them crates and adding them to a workspace, changing `cargo --bench ldbc-graphalytics -- ...args` to `cargo run ldbc-graphalytics ...args`

**Comment by mihaibudiu** [comment]
Can we close this issue?
