### ISSUE TITLE
JSON DDL format changes

### ISSUE THREAD

**Issue by gz** [feldera/dbsp#410]
It would be good to change the format for some types in the DDL description of the JSON to make it easier to parse for clients:

```
VARCHAR(X) -> { type: VARCHAR, length: X}
ARRAY BIGINT -> { type: ARRAY, subtype: BIGINT }
DECIMAL/NUMERIC -> { type: DECIMAL, precision: number, scale: number }
```

- when I do TIMESTAMP it reports the type as TIMESTAMP(0) -> I'm not sure what the (0) means here and if it has a meaning we can factor it also out in a field?
- There are several names for `VARCHAR(n), or CHAR(n), or CHARACTER(n), or CHARACTER VARYING(n)`, maybe we cna just always report as VARCHAR if you think that's sensible (but not a big deal if can't do that)
- Same for NUMERIC maybe we can always report DECIMAL if they're synonyms?
- I don't know GEOMETRY and INTERVAL but interval also may have 'a' and 'b' components?

**Comment by mihaibudiu** [comment]
char and varchar are not the same type
if you are lucky Calcite will already use a canonical type name

**Comment by gz** [comment]
>  if you are lucky Calcite will already use a canonical type name
looks like it does
