### ISSUE TITLE
Split `dbsp_adapters` crate into two.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#48]
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Fri Feb 10 16:35:52 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/299_

----

Move the HTTP server module into a separate crate.

**Comment by mihaibudiu** [comment]
I think this can be closed, since the server seems to be in the adapters crate.
