### ISSUE TITLE
editor reports error: Outdated program version. Expected version: 'x'

### ISSUE THREAD

**Issue by gz** [feldera/dbsp#484]
workaround is to reload the editor page
not clear what causes this but I suspect a new update for sql is being sent before acknowledgement of old version has been received from backend ... workarounds: just try to save again, or make version optional or ditch version

**Comment by lalithsuresh** [comment]
"not clear what causes this but I suspect a new update for sql is being sent before acknowledgement of old version has been received from backend"

Do you have a trace or something you can share? It sounds like there are multiple concurrent save requests being issued, in which case the correct behavior is to reject outdated versions.
