### ISSUE TITLE
RUSTSEC-2021-0147: `daemonize` is Unmaintained

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#49]
<a href="https://github.com/apps/github-actions"><img src="https://avatars.githubusercontent.com/in/15368?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [github-actions[bot]](https://github.com/apps/github-actions)**
_Mon Feb 20 00:23:31 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/304_

----

> `daemonize` is Unmaintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `daemonize`                      |
| Version             | `0.4.1`                   |
| URL                 | [https://github.com/knsd/daemonize/issues/46](https://github.com/knsd/daemonize/issues/46) |
| Date                | 2021-09-01                         |

Last release was over four years ago.

The crate contains undocumented unsafe behind safe fns.

An [issue](https://github.com/knsd/daemonize/issues/46) inquiring as to possible updates has gone unanswered by the maintainer.

## Possible Alternatives

The below list has not been vetted in any way and may or may not contain alternatives:

- [daemonize-me](https://crates.io/crates/daemonize-me)
- [tetsy-daemonize](https://crates.io/crates/tetsy-daemonize)

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2021-0147.html) for additional details.

**Comment by mihaibudiu** [comment]
This is one that dependabot does not complain about

**Comment by ryzhyk** [comment]
I've upgraded to `daemonize 0.5`
