### ISSUE TITLE
[RFC] OOM pipeline killer

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#495]
Pipelines can use a lot of memory, causing the entire system to OOM. The OS will eventually kill the pipeline with the largest memory footprint, but this can render the entire system unresponsive for some time and overall doesn't seem like a good user experience. A short-term solution (until we have persistence) is to monitor the memory usage of the pipelines and the overall amount of available memory in the system and take a proactive action when the memory is running out.  The action could be (1) shutting down the pipeline that uses the most memory or (2) pausing all pipelines and refusing to restart them until more memory is available (e.g., because the user shut down some of the pipelines manually).

The triggering condition would depend on three main parameters: (1) total physical memory in the system, (2) total memory used by all DBSP pipelines, (3) remaining available memory. If we go down this path, we should ideally also report pipeline memory usage in the UI.

I am not too thrilled about this proposal, as it seems hard to get this right. Ideally we want the mechanism to kick in before the system becomes unresponsive and before the Linux OOM killer kicks in, but not too early, so that we don't stop pipelines that could continue running happily.  I am not sure how to achieve this given the complexity of the memory management system in Linux and the number of configuration knobs it supports.

An alternative is to add memory monitoring capabilities to the backend/UI and make sure the user understands how much memory each pipeline uses and can act accordingly. I can easily add these metrics to pipeline stats.

**Comment by mohsinbeg** [comment]
Or elicit from the user a GiB limit for the pipeline as part of the config and use cgroups to limit the pipeline PID in the container.

**Comment by ryzhyk** [comment]
That makes sense.  Problem is that in practice most users don't care. They just want Feldera to use the available memory without rendering the system unusable. Sure, we can punt the decision to them, but how likely are they to get it right (i.e., set a limit that is not too big or too small)? This is probably something we will want for production deployments, but for a downloadable playground this is probably not very practical.

**Comment by gz** [comment]
> I am not sure how to achieve this given the complexity of the memory management system in Linux and the number of configuration knobs it supports.

Maybe a [Kalman filter](https://www.bzarg.com/p/how-a-kalman-filter-works-in-pictures/) can work here. You have a process that consumes memory with a given velocity and it moves towards a boundary that you don't want to cross. You also have a set of concurrent (unknown) processes that move simultaneously and move the boundary you don't want to cross. There are some rust implementations for it, it seems.

**Comment by ryzhyk** [comment]
Not sure I understand.  None of these are unknowns, we should be able to determine pipeline memory usage and remaining available memory pretty accurately from `/proc`.  The tricky part is choosing the threshold.  I haven't used Kalman filter before, so I'm probably missing something.

**Comment by gz** [comment]
I am not sure if you see all variables you are interested in (consumption of other processes etc.?) when running in a container -- if thats possible then yes probably can do better than estimate with kalman.
