### ISSUE TITLE
Web console: display pipeline id

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#505]
The user needs to know pipeline id to interact with it via the Rest API, e.g., send data with `curl`. Currently, it needs to be extracted from the URL in the browser or from the log.  It would be nice to show it inside the UI.

**Comment by gz** [comment]
we should probably put it in configuration here: 
<img width="538" alt="image" src="https://github.com/feldera/dbsp/assets/127654/4f0890d7-47f9-4f9d-b6fa-4a8bbc9b3986">

**Comment by ryzhyk** [comment]
This was my first instinct, but the config is only displayed when the pipeline is running.

**Comment by gz** [comment]
for most of the REST/CURL things you would do, e.g., to send data you'd need pipeline running so this should be fine if only visible then? 

we could also make it a hidden column in the table that can be enabled but always show it seems a bit noisy as the id's are quite long.

**Comment by ryzhyk** [comment]
Perhaps it could also be displayed in the pipeline builder?

**Comment by gz** [comment]
in builder you can just grab it from URL I think that's acceptable? 

the thing with displaying it in the builder is that there is a time (when the pipeline doesn't exist yet) where there is no id for it yet (until the first time it's saved) so then it would suddenly pop-up not terrible, but also not great IMO

I am not sure putting IDs everywhere in the UI is the way to go -- ideally the point of the UI should be to reduce some complexity (for one thing you don't have to deal with IDs), so putting ids back everywhere defeats the purpose a bit, of course there is a fluent boundary between UI usage and CURL/SDK usage but I think it's ok to expect some "advanced" skills like reading a ID from a URL or from the config tab (or use REST to query by name to find it the id) if one wants to use the REST API

**Comment by ryzhyk** [comment]
fair enough
