### ISSUE TITLE
RUSTSEC-2019-0040: `boxfnonce` obsolete with release of Rust 1.35.0

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#52]
<a href="https://github.com/apps/github-actions"><img src="https://avatars.githubusercontent.com/in/15368?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [github-actions[bot]](https://github.com/apps/github-actions)**
_Mon Mar 13 00:21:03 2023_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/328_

----

> `boxfnonce` obsolete with release of Rust 1.35.0

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `boxfnonce`                      |
| Version             | `0.1.1`                   |
| URL                 | [https://github.com/stbuehler/rust-boxfnonce/commit/058ac7e1a7d732076da9d8a37baa66bcb67758d8](https://github.com/stbuehler/rust-boxfnonce/commit/058ac7e1a7d732076da9d8a37baa66bcb67758d8) |
| Date                | 2019-06-20                         |

[This](https://github.com/stbuehler/rust-boxfnonce/commit/058ac7e1a7d732076da9d8a37baa66bcb67758d8) commit marks the `boxfnonce` crate as obsolete and the GitHub repo has since been archived.

The functionality of `boxfnonce` has been added to Rust since 1.35.0. Use `Box&lt;dyn FnOnce(...) -&gt; ...&gt;`.

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2019-0040.html) for additional details.

**Comment by mihaibudiu** [comment]
I don't see boxfnonce used anywhere. Maybe the spelling is different? Or can we close this?

**Comment by blp** [comment]
I don't think we use it. I don't see it in the output of `cargo tree`. I think we can close this.
