### ISSUE TITLE
Dump circuits to `.dot` or some other graph format.

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#8]
<a href="https://github.com/ryzhyk"><img src="https://avatars.githubusercontent.com/u/8323135?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryzhyk](https://github.com/ryzhyk)**
_Wed Jan  5 16:50:41 2022_
_Originally opened as https://github.com/vmware/database-stream-processor/issues/12_

----

None

**Comment by mihaibudiu** [comment]
The SQL compiler already supports this. Do we need more?

**Comment by ryzhyk** [comment]
So does the `dbsp` library.  I'll close this.  We do need to build much better visualization as part of our interactive profiler.
