### ISSUE TITLE
Web UI: Test data entry

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#82]
- [x] UI to allow users to manually generate test inputs. Should enforce table schema. Should support import from CSV.
- [x] Data generator to produce bulk records for performance testing as well as to generate small test inputs for UI-based testing/debugging.
- [x] Both of the above will require the SQL compiler to output schema definitions in some form.

**Comment by gz** [comment]
Random generator support:

- [ ] BOOLEAN, or BOOL
- [x]  TINYINT
- [x]  SMALLINT, or INT2
- [x]  INTEGER, or INT, or SIGNED, or INT4
- [x] BIGINT, or INT64
- [ ] DECIMAL(precision, scale), or NUMERIC(precision, scale), or NUMBER(precision, scale)
- [ ] FLOAT, or FLOAT4, or FLOAT32, an IEEE 32-bit floating point number
- [ ] DOUBLE, or FLOAT8, or FLOAT32, an IEEE 64-bit floating point number
- [x] VARCHAR(n):
- [x] CHAR(n): or CHARACTER(n), or CHARACTER VARYING(n)
- [x] VARCHAR, or STRING, or TEXT: a string of unlimited length
- [ ] TIME
- [ ] TIMESTAMP
- [ ] DATE
- [ ] GEOMETRY
- [ ] ARRAY

Don't need to support:
- INTERVAL: can only show up in views
- NULL: can only show up in views

**Comment by gz** [comment]
I'm going to close this and make new issues for remaining things. e.g., we don't support the `GEOMETRY` type yet. And for arrays we need to fix this https://github.com/feldera/dbsp/issues/435
