### ISSUE TITLE
Streamline the UI

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#85]
The UI has some small usability issues. Would be nice to resolve some of them to make life easier for users:
- [ ] SQL editor page: there is too much basically unused space at the top of the page.
- [ ] Streamline the typical edit SQL -> configure pipeline -> right pipeline workflow (which now requires jumping between 4 different views).
- [ ] I find the main menu confusing. The "SQL Editor" page should really be called "New SQL program".  Perhaps the only items in the main menu should be "SQL Programs", "Pipelines", and "Connectors".  Whereas "New program", "New connector", and "New pipeline" should be available as actions inside corresponding pages. We may want to find some beta testers to help us improve the UI.

**Comment by Karakatiza666** [comment]
partial: https://github.com/feldera/dbsp/pull/445

**Comment by Karakatiza666** [comment]
Resolved with https://github.com/feldera/dbsp/pull/445
