### ISSUE TITLE
Getting started documentation for product

### ISSUE THREAD

**Issue by ryzhyk** [feldera/dbsp#86]
Docs to download and run Feldera, explore the UI using pre-packaged examples, build and test your own first program using UI, build an API-based client.

**Comment by blp** [comment]
This is partly on feldera.com, to direct people where to go and get started, and partly in the product (e.g. even in the README).

**Comment by gz** [comment]
some leftover issues for docs.feldera.io
- [ ] Add search bar
- [ ] The execute button in the REST API docs should work (e.g., there is an option to add multiple URLs one of them could be localhost:8080)
- [ ] deploy, develop, explore on the front page of docs should be clickable
- [ ] release dbsp on docs.rs
- [ ] complete markdown files
- [ ] write a first blog post/announcement

**Comment by blp** [comment]
@mohsinbeg You can look at https://docs.feldera.io/docs/what-is-dbsp and https://docs.feldera.io/docs/intro to see what's here so far.

**Comment by blp** [comment]
Here's the outline that @mohsinbeg suggested to me. Saving it here so it doesn't get lost.

```
    What is Feldera
        Getting Started
        Introduction
        Concepts
            Incremental data processing
            Optimizer
            Indexes
            DBSP runtime engine
        Tutorials
            Hello World
            SecOps
            …
        UI
        API
    Roadmap
    Architecture
        Components
        Ports, Network Connectivity
        Storage
        Scale up/out
        Fault Tolerance
            Read
            Write
            Processing
        Dependencies
        Dial Home Telemetry
    Deployment
        System Requirements
        Self-Managed
            docker compose
            k8s
        BYOC
            AWS
            GCP
        Scaling Up / Out
        Monitoring
            Logs, metrics
        Lifecycle Mgmt. & Upgrade
        Troubleshooting and debugging
    Configuration
    Features
        Tables and Views
        Pipelines
            Run / Pause
            Troubleshoot
            Performance
        Connectors
            Input and Output
    API Reference
    SQL Reference
    UI Reference
    Release Notes
    How to contribute
```

**Comment by blp** [comment]
I started in on this with PR #346 and PR #350.

**Comment by blp** [comment]
There have been some more commits and it's getting to be better.

**Comment by blp** [comment]
I've merged the documentation that I'm planning to write at the moment.

**Comment by blp** [comment]
I'm considering this done, for now.
